---
feature:
  entitySet:
    id: entity set id
  entities:
  - id: entity id
    entitySet: entity set id
    variable_types:
    - column_name1: Variable type
      column_name2: Variable type
    index: name of id column
    time_index: name of time column
    dataframe_path: path to dataset file
  relationship:
  - table1:
      name: table name
      column: column name
    table2:
      name: table name
      column: column name
  primitives:
  - add_numeric
  - multiply_numeric
model:
  sklearn.naive_bayes.BernoulliNB:
    alpha:
    - 0.001
    - 0.01
    - 0.1
    - 1
    - 10
    - 100
    fit_prior:
    - true
    - false
training_mode:
  mode: classifiacation
  gen: 20
  population: 100
  cv: 5
  n_jobs: -1
  scoring_function:
